import {
  defineNuxtModule,
  createResolver,
  addTemplate,
  addPlugin,
  addTypeTemplate,
} from '@nuxt/kit'

import { defaults } from './config'

import type { Options } from './types'

export default defineNuxtModule<Options>({
  meta: {
    name: '@spruce-hub/nuxt-route',
    configKey: 'nuxtRoute',
    compatibility: {
      nuxt: '^3.2.0',
    },
  },
  defaults,
  setup(_options) {
    const { resolve } = createResolver(import.meta.url)

    /** add route options template
     * -------------------------- */
    addTemplate({
      filename: 'spruce-module-route.mjs',
      write: true,
      getContents: () => {
        return `export default ${JSON.stringify(_options, null, 2)}`
      },
    })

    /** add route middleware
     * -------------------------- */
    addPlugin(resolve('./runtime/plugins/authentication'))

    addTypeTemplate({
      filename: 'types/route-module.d.ts',
      getContents: () => `// Generated by @spruce-hub/nuxt-route
import type { CookieOptions } from '#app'
declare module '#app' {
  interface NuxtApp {
    /**
     * @Describe 登录成功后调用
     * @param {string} token 将要写入 cookie 的值， name 为 nuxtRoute.cookieName
     * @param {CookieOptions | string} options 当为 object 类型时，作为 useCookie 的 options；当为 string 类型时，作为重定向路由地址
     * @param {string} to 重定向路由地址，该项具有最高优先级
     */
    $loginSuccess(token: string): void
    $loginSuccess(token: string, to: string): void
    $loginSuccess(token: string, options: CookieOptions, to?: string): void
    $loginSuccess(token: string, options?: CookieOptions | string, to?: string): void

    /**
     * @Describe 记录一个路由地址并跳转到登录页
     * @param {string} fullPath 记录的路由地址
     */
    $toLogin(fullPath: string): void
  }
}
declare module 'vue' {
  interface ComponentCustomProperties {
    /**
     * @Describe 登录成功后调用
     * @param {string} token 将要写入 cookie 的值， name 为 nuxtRoute.cookieName
     * @param {CookieOptions | string} options 当为 object 类型时，作为 useCookie 的 options；当为 string 类型时，作为重定向路由地址
     * @param {string} to 重定向路由地址，该项具有最高优先级
     */
    $loginSuccess(token: string): void
    $loginSuccess(token: string, to: string): void
    $loginSuccess(token: string, options: CookieOptions, to?: string): void
    $loginSuccess(token: string, options?: CookieOptions | string, to?: string): void

    /**
     * @Describe 记录一个路由地址并跳转到登录页
     * @param {string} fullPath 记录的路由地址
     */
    $toLogin(fullPath: string): void
  }
}
declare module "@vue/runtime-core" {
  interface ComponentCustomProperties {
    /**
     * @Describe 登录成功后调用
     * @param {string} token 将要写入 cookie 的值， name 为 nuxtRoute.cookieName
     * @param {CookieOptions | string} options 当为 object 类型时，作为 useCookie 的 options；当为 string 类型时，作为重定向路由地址
     * @param {string} to 重定向路由地址，该项具有最高优先级
     */
    $loginSuccess(token: string): void
    $loginSuccess(token: string, to: string): void
    $loginSuccess(token: string, options: CookieOptions, to?: string): void
    $loginSuccess(token: string, options?: CookieOptions | string, to?: string): void

    /**
     * @Describe 记录一个路由地址并跳转到登录页
     * @param {string} fullPath 记录的路由地址
     */
    $toLogin(fullPath: string): void
  }
}
export {}`,
    })
  },
})
