import {
  defineNuxtModule,
  createResolver,
  addTemplate,
  addPlugin,
  addTypeTemplate,
} from '@nuxt/kit'

import { defaults } from './config'

import type { Options } from './types'

export default defineNuxtModule<Options>({
  meta: {
    name: '@spruce-hub/nuxt-route',
    configKey: 'nuxtRoute',
    compatibility: {
      nuxt: '^3.2.0',
    },
  },
  defaults,
  setup(_options) {
    const { resolve } = createResolver(import.meta.url)

    /** add route options template
     * -------------------------- */
    addTemplate({
      filename: 'spruce-module-route.mjs',
      write: true,
      getContents: () => {
        return `export default ${JSON.stringify(_options, null, 2)}`
      },
    })

    /** add route middleware
     * -------------------------- */
    addPlugin(resolve('./runtime/plugins/authentication'))

    addTypeTemplate({
      filename: 'types/route-module.d.ts',
      getContents: () => `// Generated by @spruce-hub/nuxt-route
import type { CookieOptions } from '#app'
declare module '#app' {
  interface NuxtApp {
    $loginSuccess(token: string, options?: CookieOptions): void
  }
}
declare module 'vue' {
  interface ComponentCustomProperties {
    $loginSuccess(token: string, options?: CookieOptions): void
  }
}
declare module "@vue/runtime-core" {
  interface ComponentCustomProperties {
    $loginSuccess(token: string, options?: CookieOptions): void
  }
}
export {}`,
    })
  },
})
